### ISSUE TITLE
First 5 tests fail due to misplaced location of the module

### ISSUE THREAD

**Issue by ybarlev** [sdsc/gnucompiler-roll#5]
The tests load "module load gnu", while module file is located at "module load compilers/gnu"
I think I saw others rolls who load the module as "module load gnu", so maybe it is better to deploy the module file accordingly.

**Comment by jjhayes** [comment]
The SDSC rolls place modulefiles in subdirectories (compilers, applications, mpi) underneath /opt/modulefiles.  The sdsc-roll, along with other steps, installs /etc/profile.d/sdsc.{csh,sh}, one function of which is to add these subdirectories to the MODULEPATH environment variable.  If those /etc/profile.d files are in place, the tests should pass.

Jim

**Comment by ybarlev** [comment]
The point is that this assumes there ARE sub-directories in "/opt/modulefiles",
which contradicts the commons installation flow.
First you install sdsc-roll, which is required for the majority of the
other sdsc rolls. At this stage there are no sub-directories, and in fact
there is no  "/opt/modulefiles".
This is at least was my flow of installation, which first resulted in the
/rollstests/sdsc.t bug I have previously reported.

**Comment by jjhayes** [comment]
Correct.  That's a bug in sdsc.t; I pushed out a fix for that this morning.

**Comment by tcooper** [comment]
Fixed in [this commit](https://github.com/sdsc/sdsc-roll/commit/991dba748cc2ed25ee28c53ca120b78ff73c4874).
