### ISSUE TITLE
make in gnucompiler-roll

### ISSUE THREAD

**Issue by sharmaprajesh** [sdsc/gnucompiler-roll#6]
I am using a rocks cluster and with following rolls
ganglia:     6.2      x86_64 yes    
kernel:      6.2      x86_64 yes    
hpc:         6.2      x86_64 yes    
perfSONAR:   3.4.2    x86_64 yes    
web-server:  6.2      x86_64 yes    
python:      6.2      x86_64 yes    
htcondor:    8.2.8    x86_64 yes    
java:        6.2      x86_64 yes    
bio:         6.2      x86_64 yes    
fingerprint: 6.2      x86_64 yes    
perl:        6.2      x86_64 yes    
sge:         6.2      x86_64 yes    
base:        6.2      x86_64 yes    
kvm:         6.2      x86_64 yes    
os:          6.2      x86_64 yes    
sdsc:        master.0 x86_64 yes    <---------
cmake:       master.0 x86_64 yes    <--------------
gnutools:    master.0 x86_64 yes    <-------------

Now, I need to install gnucompiler roll for cern roll installation, but when i ran make command
it show me errors after some logn output:
=======================
...
g++ -c   -g -DIN_GCC    -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wwrite-strings -Wcast-qual -Wno-format -Wmissing-format-attribute -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings -fno-common  -DHAVE_CONFIG_H -I. -I. -I../.././gcc -I../.././gcc/. -I../.././gcc/../include -I../.././gcc/../libcpp/include -I/root/extraRoll/gnucompiler/gnucompiler-roll-master/BUILD/sdsc-gcc-4.9.2/../..//cache/gmp/include -I/root/extraRoll/gnucompiler/gnucompiler-roll-master/BUILD/sdsc-gcc-4.9.2/../..//cache/mpfr/include -I/root/extraRoll/gnucompiler/gnucompiler-roll-master/BUILD/sdsc-gcc-4.9.2/../..//cache/mpc/include  -I../.././gcc/../libdecnumber -I../.././gcc/../libdecnumber/bid -I../libdecnumber -I../.././gcc/../libbacktrace    -o gimplify-me.o -MT gimplify-me.o -MMD -MP -MF ./.deps/gimplify-me.TPo ../.././gcc/gimplify-me.c
make[8]: *** [s-attrtab] Killed
make[8]: *** Waiting for unfinished jobs....
/bin/sh ../.././gcc/../move-if-change tmp-automata.c insn-automata.c
echo timestamp > s-automata
rm gcc.pod
make[8]: Leaving directory `/root/extraRoll/gnucompiler/gnucompiler-roll-master/BUILD/sdsc-gcc-4.9.2/gcc-4.9.2/host-x86_64-unknown-linux-gnu/gcc'
make[7]: *** [all-stage1-gcc] Error 2
make[7]: Leaving directory `/root/extraRoll/gnucompiler/gnucompiler-roll-master/BUILD/sdsc-gcc-4.9.2/gcc-4.9.2'
make[6]: *** [stage1-bubble] Error 2
make[6]: Leaving directory `/root/extraRoll/gnucompiler/gnucompiler-roll-master/BUILD/sdsc-gcc-4.9.2/gcc-4.9.2'
make[5]: *** [all] Error 2
make[5]: Leaving directory `/root/extraRoll/gnucompiler/gnucompiler-roll-master/BUILD/sdsc-gcc-4.9.2/gcc-4.9.2'
make[4]: *** [build] Error 2
make[4]: Leaving directory `/root/extraRoll/gnucompiler/gnucompiler-roll-master/BUILD/sdsc-gcc-4.9.2'
make[3]: *** [build] Error 2
make[3]: Leaving directory `/root/extraRoll/gnucompiler/gnucompiler-roll-master/BUILD/sdsc-gcc-4.9.2'
error: Bad exit status from /var/tmp/rpm-tmp.WpD6EV (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.WpD6EV (%build)
make[2]: *** [rpm] Error 1
make[2]: Leaving directory `/root/extraRoll/gnucompiler/gnucompiler-roll-master/src/gcc'
make[1]: *** [rpm] Error 2
make[1]: Leaving directory `/root/extraRoll/gnucompiler/gnucompiler-roll-master/src'
make: *** [rpms] Error 2
==============================================
I did it many times but same error display, I did not understand why this happening. Please tell
me where is problem. 
Thanks.

**Comment by jjhayes** [comment]
I haven't been able to re-create this--my builds of the gnucompiler-roll succeed when building from either a git clone or from the v6.2 tar.gz package.  The first error you encounter:

make[8]: *** [s-attrtab] Killed

looks to me like a system out-of-memory error.  Can you look at /var/log/messages to see if there's any indication that the system might have killed your build?

**Comment by sharmaprajesh** [comment]
Thank you very much.
I have install gnu compiler roll successfully.
