### ISSUE TITLE
GCC Module not available after installation :( 

### ISSUE THREAD

**Issue by ucerd** [sdsc/gnucompiler-roll#7]
First of all thanks for the roll
I am able to install it without any error

after installation its visible in
rocks list roll

But not availbable in
/opt/modulefiles/compilers/gnu

Neither testing file present
/root/rolltests/gnucompiler.t 

module avail also does not show gnu/gcc roll

**Comment by tcooper** [comment]
Please confirm that you performed all steps described in the [Installation](https://github.com/sdsc/gnucompiler-roll#installation) section of the README for this roll. It appears that may only have installed the roll on the frontend. There are separate steps required to install the provided RPMs on nodes of your cluster.

**Comment by ucerd** [comment]
% make 2>&1 | tee build.log
created the .iso file

commands on Front-end
% rocks add roll *.iso
% rocks enable roll gnucompiler
% cd /export/rocks/install
% rocks create distro

executed without errors

You are right I am just testing it on Front-end not yet installed on compute node
On front-end I added this
% rocks run roll gnucompiler host=(front-end hostname) | bash

but not seeing gcc7 anywhere = is it only for compute nodes

**Comment by tcooper** [comment]
Per the [Installation instructions](https://github.com/sdsc/gnucompiler-roll#installation) please change the command you ran on your frontend to be of the form...
```
# rocks run roll gnucompiler host=[compute node name] | bash
```
