### ISSUE TITLE
GNU compiler Issue on Rock Cluster frontend node

### ISSUE THREAD

**Issue by usmanfarooq948** [sdsc/gnucompiler-roll#8]
Sorry i am new to Rock Distribution. How a user can compile his application using GNU compiler. As i Know Front-end node only manages software packages on cluster as well as the submitted jobs and compute-end provide the processing power.

**Comment by tcooper** [comment]
This question is appropriate for the Rocks Mailing list which you can access from [here](http://www.rocksclusters.org/docs.html).
